### ISSUE TITLE
Name "FStar.All.ML" not found

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/fstar-mode.el#20] opened 2015-09-19 21:24 UTC
Hello, I have a strange error when trying to interactively type-check some files : 
Name "FStar.All.ML" not found

This does not happen when I use FStar directly...

![screen shot 2015-09-19 at 23 20 52](https://cloud.githubusercontent.com/assets/1193431/9978234/8f0ad9a8-5f25-11e5-9e41-51ee1fe1e04c.jpg)

Any ideas ?

**Comment by cpitclaudel** [comment] 2015-09-19 21:40
That's strange. Can you post the file?

**Comment by beurdouche** [comment] 2015-09-19 21:49
It is the standard bytes.fst file from the F* repository (fstar/lib/bytes.fst) after a clean checkout... =(
Here is mine, just in case. https://infinit.io/_/g2chVAS

**Comment by cpitclaudel** [comment] 2015-09-19 22:01
Thanks. I can reproduce it.

**Comment by cpitclaudel** [comment] 2015-09-19 22:02
I would bet on an F* bug:

```shell
$ (cat bytes.fst; echo "#end") | ../bin/fstar.exe --in
<input>(5,21-5,32): Name "FStar.All.ML" not found
fail
```

**Comment by jkzinzindohoue** [comment] 2015-09-19 22:21
F* automatically includes the files st.fst and all.fst when using the command line on a single file. It may be for the tutorial, I am not sure. 
I guess it is just not happening through the interactive mode, so you should add them manually via a build config.

**Comment by markulf** [comment] 2015-09-19 23:06
We should stop automatically including st.fst and all.fst, and fix the tutorial?

**Comment by catalin-hritcu** [comment] 2015-09-20 08:03
> We should stop automatically including st.fst and all.fst, and fix the tutorial?

Completely agreed, filed this as https://github.com/FStarLang/FStar/issues/374.

**Comment by cpitclaudel** [comment] 2015-10-03 20:15
I'll close this bug, since it doesn't seem directly related to the Emacs mode.

**Closed by cpitclaudel** 2015-10-03 20:15 UTC
