### ISSUE TITLE
fstar-mode opens new buffer upon errors

### ISSUE THREAD

**Issue by kkohbrok** [FStarLang/fstar-mode.el#46] opened 2017-02-02 18:21 UTC
This might be a design decision, but I find that opening a (new) split buffer to display error messages is a bit intrusive.
Type checking the following code in interactive-mode, it opens a new buffer to display the error instead of displaying it at the bottom of the existing buffer.
```
module Test

open FStar.Seq

type x = na
```

**Comment by cpitclaudel** [comment] 2017-02-05 20:39
Can you try reproducign this in a clean Emacs (`-Q`)? The behavior your describe  is not what fstar-mode does by default, so I'd tend to blame your config (Did you customize `show-help-function`?).

**Comment by kkohbrok** [comment] 2017-02-05 21:24
Sorry, I'm not that familiar with emacs, which makes my config a likely candidate, however, the only thing that changed before those splits started appearing was an update of fstar-mode.
so what I did now was the following:
- get a clean .emacs and .emacs.d
- start emacs, install fstar-mode
- restart emacs, try verifying a file
-> got the same error

I would also try it with emacs -Q, but I did not manage using/installing fstar-mode with that method.
Again, sorry for my inaptitude with emacs. I will gladly provide logs/configs, whatever you need.

**Comment by cpitclaudel** [comment] 2017-02-05 21:39
Thanks for your help.  I think a screenshot would help :) It might also be *my* config that makes things work nicely for me :)

**Comment by kkohbrok** [comment] 2017-02-06 14:57
![bildschirmfoto von 2017-02-06 14-49-58](https://cloud.githubusercontent.com/assets/9829662/22651798/0be370fe-ec7c-11e6-8f61-8a6528e9f00b.png)
You have the config in the terminal on the left and minimal F* example on the right.
Upon pressing C-x C-n, the window splits and displays the warning on the lower buffer.
The behaviour is the same in X emacs (as opposed to emacs with the -nw flag that is visible in the screenshot).

**Comment by cpitclaudel** [comment] 2017-02-06 15:25
Thanks, that clarifies it a lot :) This sounds like an F* issue, at least in part.  F* mode warns you loudly (as you can see) when F* warns about an error in a file that isn't the current file.  Here, F* claims that the error came from FStar.Seq.Properties.fst, which isn't the current file.  @aseemr, ideas?

**Comment by kkohbrok** [comment] 2017-02-06 15:29
I do get the same buffer split with warnings such as:
> Warning (emacs): Non-empty response despite prover success: [<input>(46,8-46,55): (Warning) Top-level let-bindings must be total; this term may have effects]

**Comment by cpitclaudel** [comment] 2017-02-06 15:35
up; that one is on the fstar-mode side.  When I originally wrote it, F* didn't issue warnings like this one.  An update would be good.   I wonder what the UI should be like, though: should the warnings persist (like errros?), or should they be displayed in the echo area and fade after a small amount of time?  I'd guess persisting would be better, right?

**Comment by kkohbrok** [comment] 2017-02-06 15:41
For my taste, I would like the warning to persist in the echo area. It would be nice to hear some more opinions on this, though. I guess it's a matter of preference/workflow.

**Comment by s-zanella** [comment] 2017-02-06 16:10
@cpitclaudel: See #45 for F* reporting errors in other files (in that case, F* is to blame).
I prefer warnings to persist like errors do.

**Comment by cpitclaudel** [comment] 2017-02-06 16:21
@s-zanella Woops, not sure how I missed that other thread. Thanks!
I'll close this issue when I implement support for `(Warning)` messages then, and we can track the other one in #45.

**Comment by markulf** [comment] 2017-02-07 18:04
Persisting warnings is good. Maybe the mini-buffer should display the first error rather than the first warning, to ease navigation.

**Comment by cpitclaudel** [comment] 2017-02-07 21:40
Ok, I've pushed a draft to https://github.com/FStarLang/fstar-mode.el/tree/46-warning-popups :) @kkohbrok, can you have a look? It should show warnings as orange underlines.

**Comment by kkohbrok** [comment] 2017-02-08 08:48
Ok, so I removed the elpa pkg fstar-mode and manually loaded the patched fstar-mode.el version.
After going into fstar-mode, it still displays the warnings in a separate buffer.
![bildschirmfoto von 2017-02-08 08-46-52](https://cloud.githubusercontent.com/assets/9829662/22729578/42c674da-eddb-11e6-98b6-5a67c16b5d69.png)

**Comment by s-zanella** [comment] 2017-02-08 12:03
@kkohbrok It seems that you're still using the unpatched version. Are you sure your Emacs is not loading a stale .elc file?

@cpitclaudel The behaviour improved somewhat for me: I no longer get a new Emacs windows for warnings, but warnings don't persist in the echo area as error messages do. Some warnings don't have proper location info (e.g. https://github.com/FStarLang/FStar/issues/836), so they can go easily unnoticed since they will show only in the Messages buffer and there will be no highlighting in the source buffer.

**Comment by cpitclaudel** [comment] 2017-02-08 14:58
@s-zanella Thanks for testing! 

I tried FStarLang/FStar#836, and indeed I get `unknown(0,0-0,0): (Warning) M: Unexpected output from Z3: (error "line 48305 column 20: unknown constant @x0")`.  What do you think we should do in that case? Highlight the entire overlay? (Currently it highlights the first character of the file)

Regarding persistence: can you post an example file? Thanks!

**Comment by s-zanella** [comment] 2017-02-08 15:22
I completely missed the line under the first character!

All cases of `unknown(0,0-0,0)` warnings I know of are F* bugs. Depending on whether you want to make further bugs easier to be caught in fstar-mode, you can either highlight the whole overlay or do nothing.

Best to explain the persistence issue with pictures.
The first screenshot shows an error, with the persistent message in the echo area.
The second one shows a warning, with no indication in the echo area.

![error](https://cloud.githubusercontent.com/assets/7451757/22743495/3c872c40-ee12-11e6-9180-b3a576047e59.png)
![warning](https://cloud.githubusercontent.com/assets/7451757/22743481/31dec3d4-ee12-11e6-9e0f-6dbd797a223d.png)

**Comment by cpitclaudel** [comment] 2017-02-08 15:48
Thanks for the screenshot! Does `C-h .` bring the message back?

**Comment by s-zanella** [comment] 2017-02-08 15:54
It doesn't.

**Comment by cpitclaudel** [comment] 2017-02-08 15:56
Snap. I'll look into this :)

**Comment by kkohbrok** [comment] 2017-02-08 17:44
@s-zanella you were right. I forgot to check out the correct branch.
It works for me now and looks like this:
![bildschirmfoto von 2017-02-08 17-40-01](https://cloud.githubusercontent.com/assets/9829662/22749654/fce5b5c0-ee25-11e6-8f8c-f0edce6b0520.png)

**Comment by cpitclaudel** [comment] 2017-02-09 15:20
@kkohbrok Thanks for testing.  What you're seeing is still clearly not ideal, but it'll go away too once #45 is fixed.

**Comment by cpitclaudel** [comment] 2017-02-09 16:03
@s-zanella Ah, that keybinding was introduced in Emacs 25.  I pushed the corresponding change.
I also made sure that debugging messages are only printed to the `*Messages*` buffer, and not to the echo area. This should prevent the message from disappearing in the first place.

**Comment by cpitclaudel** [comment] 2017-02-09 16:59
@s-zanella Ah, that keybinding was introduced in Emacs 25.  I pushed the corresponding change.
I also made sure that debugging messages are only printed to the `*Messages*` buffer, and not to the echo area. This should prevent the message from disappearing in the first place.

**Comment by s-zanella** [comment] 2017-02-09 17:36
Thanks! Works great. 
Those debug messages were annoying.

**Comment by cpitclaudel** [comment] 2017-02-09 18:00
Thanks. I'll close this then :)
(The messages should be off by default, btw; do you have something turning `fstar-subp-debug` on or calling `fstar-subp-toggle-debug` in your .emacs?)

**Closed by cpitclaudel** 2017-02-09 18:00 UTC

**Comment by s-zanella** [comment] 2017-02-10 10:18
Yes, I did have a `(setq fstar-subp-debug t)`. Forgot to turn it off.

**Comment by cpitclaudel** [comment] 2017-02-10 21:38
I merged the warnings branch.  Let me know if new errors pop up :)
