### ISSUE TITLE
Auto-populate match expressions

### ISSUE THREAD

**Issue by parno** [FStarLang/fstar-mode.el#60] opened 2017-05-15 18:41 UTC
Here's a random idea for a fun (but certainly not critical nor particularly F*-specific) feature: In my current code, I have a number of inductive types with a long list of possible constructors.  When I later write a match statement for such a type, I have to type in all of the possible constructors (and arguments).  Knowing very little about how emacs extensions are written, I imagine it could be possible to have such match statements populated automatically, or even interactively (in case I only want to handle a few cases explicitly).

**Comment by cpitclaudel** [comment] 2017-05-15 18:47
Are you thinking of https://github.com/FStarLang/FStar/pull/940 ?

**Comment by parno** [comment] 2017-05-15 19:01
Yep, that looks like it.  You're way ahead of me :)

**Comment by cpitclaudel** [comment] 2017-08-03 18:32
Merging this (duplicate of #58). I'm hoping to tackle this again at some point in the summer.

**Closed by cpitclaudel** 2017-08-03 18:32 UTC
